### ISSUE TITLE
程序崩溃

### ISSUE THREAD

**Issue by linbren** [fly803/BaseProject#5]
08-10 16:43:53.045 2814-2814/com.ivy.baseproject.test E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.ivy.baseproject.test, PID: 2814
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ivy.baseproject.test/me.weyye.hipermission.PermissionActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:163)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6337)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
                                                                         Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

**Comment by fly803** [comment]
注释掉这个方法，EasyPermissionUtils.hiPermission(this);刚刚提交的时候忽律了，正好被你拉下来，你在更新一下也行
